# Generated by Django 4.2.4 on 2023-08-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationsApp', '0002_alter_reservation_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='how_many',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
