# Generated by Django 4.2.4 on 2023-08-25 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantsApp', '0002_remove_restaurant_photourl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='CuisineType',
            new_name='cuisineType',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='MealType',
            new_name='mealType',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='Owner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='PhoneNumber',
            new_name='phoneNumber',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='RestaurantID',
            new_name='restaurantID',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='Services',
            new_name='services',
        ),
    ]
