# Generated by Django 4.2.4 on 2023-08-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantsApp', '0003_rename_address_restaurant_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='cuisineType',
            new_name='cuisine_type',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='mealType',
            new_name='meal_type',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='max_booking',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
