# Generated by Django 4.2.4 on 2023-08-30 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantsApp', '0004_rename_cuisinetype_restaurant_cuisine_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='max_booking',
            field=models.IntegerField(default=100),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photoID', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='media')),
                ('photo_comment', models.CharField(default='', max_length=100)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantsApp.restaurant')),
            ],
        ),
    ]
