# Generated by Django 4.2.4 on 2023-08-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantsApp', '0006_alter_restaurant_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine_type',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='meal_type',
            field=models.CharField(max_length=200),
        ),
    ]
