# Generated by Django 4.2.4 on 2023-08-30 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantsApp', '0007_alter_restaurant_cuisine_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='services',
        ),
    ]
