# Generated by Django 4.2.4 on 2023-08-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantsApp', '0010_alter_restaurant_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='average_rating',
            field=models.FloatField(default=0, null=True),
        ),
    ]
