# Generated by Django 4.2.4 on 2023-08-31 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewsApp', '0003_rename_user_review_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='ambiance_rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='cleanliness_rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='service_rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='value_price_rating',
        ),
    ]
